# Generated by Django 4.1.7 on 2023-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_proffession_profile_proffession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
