# Generated by Django 4.1.7 on 2023-02-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
